[_PROJECT]
build = "make -C build -j4"
clean = "rm -rf ./build"
config = "cmake -B build"
run = ""
target = "kappa"
target_config = "debug"
target_configs = [ "debug", "release" ]
term_dir = "vertical"
test = ""

[kappa]
run = "mangohud --dlsym ./build/kappa"

    [kappa.config]
    debug = [ "-DCMAKE_BUILD_TYPE=Debug" ]
    release = [ "-DCMAKE_BUILD_TYPE=Release" ]