[_PROJECT]
env=["GTEST_COLOR=1"]
run=""
clean="rm -rf ./build"
build="make -C build -j4"
config="cmake -B build"
target="game_test"
target_config="debug"

[game_test]
run="mangohud --dlsym ./build/game_test"

[game_test.configs]
debug=["-DCMAKE_BUILD_TYPE=Debug"]
release=["-DCMAKE_BUILD_TYPE=Release"]
