#include "./vk_common.hpp"

namespace kappa::render {

fn vk_error_string(VkResult res) noexcept -> const char* {
#define VKSTR(code) \
  case code:        \
    return #code;

  switch (res) {
    VKSTR(VK_NOT_READY);
    VKSTR(VK_TIMEOUT);
    VKSTR(VK_EVENT_SET);
    VKSTR(VK_EVENT_RESET);
    VKSTR(VK_INCOMPLETE);
    VKSTR(VK_ERROR_OUT_OF_HOST_MEMORY);
    VKSTR(VK_ERROR_OUT_OF_DEVICE_MEMORY);
    VKSTR(VK_ERROR_INITIALIZATION_FAILED);
    VKSTR(VK_ERROR_DEVICE_LOST);
    VKSTR(VK_ERROR_MEMORY_MAP_FAILED);
    VKSTR(VK_ERROR_LAYER_NOT_PRESENT);
    VKSTR(VK_ERROR_EXTENSION_NOT_PRESENT);
    VKSTR(VK_ERROR_FEATURE_NOT_PRESENT);
    VKSTR(VK_ERROR_INCOMPATIBLE_DRIVER);
    VKSTR(VK_ERROR_TOO_MANY_OBJECTS);
    VKSTR(VK_ERROR_FORMAT_NOT_SUPPORTED);
    VKSTR(VK_ERROR_SURFACE_LOST_KHR);
    VKSTR(VK_ERROR_NATIVE_WINDOW_IN_USE_KHR);
    VKSTR(VK_SUBOPTIMAL_KHR);
    VKSTR(VK_ERROR_OUT_OF_DATE_KHR);
    VKSTR(VK_ERROR_INCOMPATIBLE_DISPLAY_KHR);
    VKSTR(VK_ERROR_VALIDATION_FAILED_EXT);
    VKSTR(VK_ERROR_INVALID_SHADER_NV);
    default:
      return "UNKNOWN_ERROR";
  }
#undef VKSTR
};

} // namespace kappa::render
